language: node_js
node_js:
  - "12.13"
os: linux
dist: bionic
sudo: required


before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi

script:
  - npm version patch
  - git push https://JasonZhongZexin:${git_key}@github.com/JasonZhongZexin/SVF-Lib.git   HEAD:master
install: true

deploy:
  provider: npm
  skip_cleanup: true
  email: ${npm_email}
  api_key: ${npm_token} 